FROM python:3.13-slim

WORKDIR /code

ARG POETRY_VERSION=2.0.1

RUN pip install "poetry==$POETRY_VERSION"

COPY poetry.lock pyproject.toml ./

RUN poetry config virtualenvs.create false \
    && poetry install

COPY common/ ./common
COPY tasks/ ./tasks

# EXPOSE 8000

ENTRYPOINT [ "huey_consumer.py" ]
CMD [ "tasks.tasks.huey" ]
