from pymongo import ASCENDING, HASHED, TEXT, IndexModel

INDEX_BASE = [
    # IndexModel([("object", HASHED)]),
    # IndexModel([("card_faces.object", ASCENDING)]),
    IndexModel([("id", HASHED)]),
    IndexModel([("oracle_id", HASHED)]),
    # A reversible_card carries no top-level oracle_id - Scryfall puts one on
    # each face - so api.helpers.cards_mongo.oracle_id_match looks in both
    # places with an $or. Without this the second branch is a collection scan
    # on every card page load, whatever the layout of the card requested.
    IndexModel([("card_faces.oracle_id", ASCENDING)]),
    IndexModel([("multiverse_ids", ASCENDING)]),
    # IndexModel([("mtgo_id", HASHED)]),
    IndexModel([("arena_id", HASHED)]),
    # IndexModel([("tcgplayer_id", HASHED)]),
    IndexModel([("name", ASCENDING)]),
    IndexModel([("name_search", ASCENDING)]),
    IndexModel([("lang", HASHED)]),
    IndexModel([("released_at", ASCENDING)]),
    IndexModel([("layout", HASHED)]),
    # IndexModel([("highres_image", HASHED)]),
    # IndexModel([("image_status", HASHED)]),
    IndexModel([("cmc", ASCENDING)]),
    IndexModel([("colors", ASCENDING)]),
    # IndexModel([("card_faces.colors", ASCENDING)]),
    IndexModel([("color_identity", ASCENDING)]),
    # IndexModel([("card_faces.color_indicator", ASCENDING)]),
    IndexModel([("produced_mana", ASCENDING)]),
    IndexModel([("games", ASCENDING)]),
    IndexModel([("keywords", ASCENDING)]),
    # IndexModel([("reserved", HASHED)]),
    # IndexModel([("foil", HASHED)]),
    # IndexModel([("nonfoil", HASHED)]),
    # IndexModel([("finishes", ASCENDING)]),
    IndexModel([("oversized", HASHED)]),
    IndexModel([("promo", HASHED)]),
    IndexModel([("reprint", HASHED)]),
    IndexModel([("variation", HASHED)]),
    # IndexModel([("set_id", HASHED)]),
    IndexModel([("set", ASCENDING)]),
    IndexModel([("set_name", ASCENDING)]),
    # IndexModel([("set_type", ASCENDING)]),
    IndexModel([("collector_number", ASCENDING)]),
    IndexModel([("digital", HASHED)]),
    IndexModel([("rarity", HASHED)]),
    IndexModel([("artist", ASCENDING)]),
    # IndexModel([("artist_ids", ASCENDING)]),
    # IndexModel([("illustration_id", HASHED)]),
    # IndexModel([("card_faces.illustration_id", ASCENDING)]),
    IndexModel([("border_color", HASHED)]),
    IndexModel([("frame", HASHED)]),
    IndexModel([("full_art", HASHED)]),
    IndexModel([("textless", HASHED)]),
    IndexModel([("booster", HASHED)]),
    # IndexModel([("story_spotlight", HASHED)]),
    # IndexModel([("mtgo_foil_id", HASHED)]),
    IndexModel([("watermark", HASHED)]),
    # IndexModel([("cardmarket_id", HASHED)]),
    IndexModel([("power", ASCENDING)]),
    IndexModel([("toughness", ASCENDING)]),
    IndexModel([("edhrec_rank", ASCENDING)]),
    IndexModel([("penny_rank", ASCENDING)]),
    # IndexModel([("security_stamp", ASCENDING)]),
    # IndexModel([("legalities", HASHED)]),
    IndexModel([("legalities.standard", HASHED)]),
    IndexModel([("legalities.future", HASHED)]),
    IndexModel([("legalities.historic", HASHED)]),
    IndexModel([("legalities.timeless", HASHED)]),
    IndexModel([("legalities.gladiator", HASHED)]),
    IndexModel([("legalities.pioneer", HASHED)]),
    IndexModel([("legalities.explorer", HASHED)]),
    IndexModel([("legalities.modern", HASHED)]),
    IndexModel([("legalities.legacy", HASHED)]),
    IndexModel([("legalities.pauper", HASHED)]),
    IndexModel([("legalities.vintage", HASHED)]),
    IndexModel([("legalities.penny", HASHED)]),
    IndexModel([("legalities.commander", HASHED)]),
    IndexModel([("legalities.oathbreaker", HASHED)]),
    IndexModel([("legalities.standardbrawl", HASHED)]),
    IndexModel([("legalities.brawl", HASHED)]),
    IndexModel([("legalities.alchemy", HASHED)]),
    IndexModel([("legalities.paupercommander", HASHED)]),
    IndexModel([("legalities.duel", HASHED)]),
    IndexModel([("legalities.oldschool", HASHED)]),
    IndexModel([("legalities.premodern", HASHED)]),
    IndexModel([("legalities.predh", HASHED)]),
]

TEXT_INDEX = [
    ("name", TEXT),
    ("card_faces.name", TEXT),
    ("type_line", TEXT),
    ("card_faces.type_line", TEXT),
    ("artist", TEXT),
    ("card_faces.artist", TEXT),
    ("oracle_text", TEXT),
    ("card_faces.oracle_text", TEXT),
    ("flavor_text", TEXT),
    ("card_faces.flavor_text", TEXT),
    ("printed_name", TEXT),
    ("card_faces.printed_name", TEXT),
    ("printed_type_line", TEXT),
    ("card_faces.printed_type_line", TEXT),
    ("printed_text", TEXT),
    ("card_faces.printed_text", TEXT),
    ("flavor_name", TEXT),
    ("set_name", TEXT),
    ("set", TEXT),
    ("keywords", TEXT),
]

TEXT_INDEX_OPTION = {
    "name": "text_index",
    "weights": {
        "name": 10,
        "card_faces.name": 5,
        "artist": 10,
        "card_faces.artist": 5,
        "type_line": 10,
        "card_faces.type_line": 5,
        "oracle_text": 2,
        "card_faces.oracle_text": 1,
        "flavor_text": 2,
        "card_faces.flavor_text": 2,
        "printed_name": 5,
        "card_faces.printed_name": 5,
        "printed_type_line": 5,
        "card_faces.printed_type_line": 5,
        "printed_text": 2,
        "card_faces.printed_text": 2,
        "flavor_name": 1,
        "set_name": 10,
        "set": 10,
        "keywords": 5,
    },
}
