/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/cards/id/{scryfall_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Card By Scryfall Id
     * @description Get a specific MTG card printing by Scryfall ID.
     *
     *     Args:
     *         scryfall_id: Unique Scryfall UUID for a specific card printing
     *         collection: MongoDB cards collection (injected dependency)
     *
     *     Returns:
     *         Card data including image_uris and all metadata
     *
     *     Raises:
     *         HTTPException: 404 if card not found
     */
    get: operations["get_card_by_scryfall_id_cards_id__scryfall_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cards/oracle/{oracle_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Cards By Oracle Id
     * @description Get all printings of a card by Oracle ID.
     *
     *     Args:
     *         oracle_id: Oracle UUID representing the card concept (non-unique)
     *         collection: MongoDB cards collection (injected dependency)
     *
     *     Returns:
     *         List of all card printings sharing this oracle_id
     *
     *     Raises:
     *         HTTPException: 404 if no cards found with this oracle_id
     */
    get: operations["get_cards_by_oracle_id_cards_oracle__oracle_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cards/oracle/{oracle_id}/aggregated": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Aggregated Card By Oracle Id
     * @description Get a single card aggregated across all its printings, by Oracle ID.
     *
     *     /cards/oracle/{oracle_id} returns the raw printings. This returns the same
     *     grouped shape that /cards/search produces for each result, so a
     *     card can be rendered on its own from an Oracle ID alone rather than only
     *     from a search result.
     *
     *     Args:
     *         oracle_id: Oracle UUID representing the card concept
     *         collection: MongoDB cards collection (injected dependency)
     *
     *     Returns:
     *         Aggregated card data, including every printing under "cards"
     *
     *     Raises:
     *         HTTPException: 404 if no cards found with this oracle_id
     */
    get: operations["get_aggregated_card_by_oracle_id_cards_oracle__oracle_id__aggregated_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cards/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search Card By Text */
    get: operations["search_card_by_text_cards_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cards/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search Card By Name */
    get: operations["search_card_by_name_cards__name__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dnd/ruling/{question}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Root */
    get: operations["read_root_dnd_ruling__question__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/mtg/ruling/{question}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Root */
    get: operations["read_root_mtg_ruling__question__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ocr/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ocr File */
    post: operations["ocr_file_ocr__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Root */
    get: operations["read_root_ping_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Sets
     * @description Get all unique MTG set names.
     *
     *     Args:
     *         collection: MongoDB cards collection (injected dependency)
     *
     *     Returns:
     *         Sets object containing list of unique set names.
     */
    get: operations["get_sets_sets_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_ocr_file_ocr__post */
    Body_ocr_file_ocr__post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /**
     * CardPrinting
     * @description A single printing of a card, shaped by ``CARD_PROJECTION``.
     *
     *     Only ``id`` and ``name`` are required: the projection asks for fields
     *     that plenty of real cards simply do not carry (no watermark, no flavour
     *     text, no images on a placeholder printing), and Mongo omits a projected
     *     field entirely when the source is missing.
     */
    CardPrinting: {
      /** Artist */
      artist?: string | null;
      /** Cmc */
      cmc?: number | null;
      /**
       * Color Identity
       * @description Colour codes. Normally W, U, B, R or G; colourless is usually an empty list, though some sources write the code C instead. Not validated against a fixed set - an unrecognised code is passed through rather than failing the response.
       */
      color_identity?: string[] | null;
      /**
       * Colors
       * @description Colour codes. Normally W, U, B, R or G; colourless is usually an empty list, though some sources write the code C instead. Not validated against a fixed set - an unrecognised code is passed through rather than failing the response.
       */
      colors?: string[] | null;
      /** Faces Thumbnails */
      faces_thumbnails?: string[] | null;
      /** Flavor Name */
      flavor_name?: string | null;
      /** Flavor Text */
      flavor_text?: string | null;
      /** Games */
      games?: string[] | null;
      /** Id */
      id: string;
      /** Image */
      image?: string | null;
      /** Imagexl */
      imageXL?: string | null;
      /** Image Uris */
      image_uris?: {
        [key: string]: string | null;
      } | null;
      /** Lang */
      lang?: string | null;
      /** Layout */
      layout?: string | null;
      /** Mana Cost */
      mana_cost?: string | null;
      /** Name */
      name: string;
      /** Oracle Id */
      oracle_id?: string | null;
      /** Oracle Text */
      oracle_text?: string | null;
      /** Penny Rank */
      penny_rank?: number | null;
      /** Printed Name */
      printed_name?: string | null;
      /** Promo */
      promo?: boolean | null;
      /** Rarity */
      rarity?: string | null;
      /** Related Uris */
      related_uris?: {
        [key: string]: string | null;
      } | null;
      /** Released At */
      released_at?: string | null;
      /** Reprint */
      reprint?: boolean | null;
      /** Security Stamp */
      security_stamp?: string | null;
      /** Set */
      set?: string | null;
      /** Set Name */
      set_name?: string | null;
      /** Thumbnail */
      thumbnail?: string | null;
      /** Type Line */
      type_line?: string | null;
      /** Variation */
      variation?: boolean | null;
      /** Variation Of */
      variation_of?: string | null;
      /** Watermark */
      watermark?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * OracleCard
     * @description A card aggregated across its printings, shaped by ``AGGREGATE_CARD``.
     *
     *     ``id`` is the oracle id the group was keyed on, and it is required. That
     *     is the one piece of strictness worth an outage: it is the value every
     *     client builds a card URL from, and while it lived only in ``_expose_id``
     *     it was a convention rather than a contract. Declaring it required turns
     *     a group with no oracle id - what a ``reversible_card`` layout produces,
     *     since Scryfall puts the oracle id on each face instead of the card -
     *     into a loud failure at the boundary instead of an empty ``href``.
     */
    OracleCard: {
      /** Card Count */
      card_count: number;
      /** Card Text */
      card_text?: string | null;
      /** Cards */
      cards: components["schemas"]["CardPrinting"][];
      /** Cmc */
      cmc?: number | null;
      /**
       * Colors
       * @description Colour codes. Normally W, U, B, R or G; colourless is usually an empty list, though some sources write the code C instead. Not validated against a fixed set - an unrecognised code is passed through rather than failing the response.
       */
      colors?: string[] | null;
      /** Faces Thumbnails */
      faces_thumbnails?: string[] | null;
      /** Id */
      id: string;
      /** Mana Cost */
      mana_cost?: string | null;
      /** Name */
      name: string;
      /** Penny Rank */
      penny_rank?: number | null;
      /** Rarity */
      rarity?: string | null;
      /** Thumbnail */
      thumbnail?: string | null;
      /** Type Line */
      type_line?: string | null;
    };
    /**
     * SearchResponse
     * @description A page of search results plus the cursor that continues it.
     */
    SearchResponse: {
      /** Cards */
      cards: components["schemas"]["SearchResultCard"][];
      /** Cursor */
      cursor?: string | null;
      /** Has More */
      has_more: boolean;
      /** Total */
      total: number;
    };
    /**
     * SearchResultCard
     * @description An :class:`OracleCard` carrying the relevance score that ranked it.
     *
     *     Only search produces a score, so it is declared here rather than on
     *     ``OracleCard``: the aggregated endpoint should not advertise a field it
     *     never returns. The score is also what the pagination cursor is built
     *     from, which makes it worth exposing rather than hiding.
     */
    SearchResultCard: {
      /** Card Count */
      card_count: number;
      /** Card Text */
      card_text?: string | null;
      /** Cards */
      cards: components["schemas"]["CardPrinting"][];
      /** Cmc */
      cmc?: number | null;
      /**
       * Colors
       * @description Colour codes. Normally W, U, B, R or G; colourless is usually an empty list, though some sources write the code C instead. Not validated against a fixed set - an unrecognised code is passed through rather than failing the response.
       */
      colors?: string[] | null;
      /** Faces Thumbnails */
      faces_thumbnails?: string[] | null;
      /** Id */
      id: string;
      /** Mana Cost */
      mana_cost?: string | null;
      /** Name */
      name: string;
      /** Penny Rank */
      penny_rank?: number | null;
      /** Rarity */
      rarity?: string | null;
      /** Score */
      score?: number | null;
      /** Thumbnail */
      thumbnail?: string | null;
      /** Type Line */
      type_line?: string | null;
    };
    /** Sets */
    Sets: {
      /** Sets */
      sets: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_card_by_scryfall_id_cards_id__scryfall_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scryfall_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardPrinting"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_cards_by_oracle_id_cards_oracle__oracle_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        oracle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardPrinting"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_aggregated_card_by_oracle_id_cards_oracle__oracle_id__aggregated_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        oracle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OracleCard"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_card_by_text_cards_search_get: {
    parameters: {
      query: {
        /** @description Full-text search query. A query parameter rather than a path segment because card names contain '//' - Fire // Ice, and every split or transforming card - and a path segment cannot carry one whatever the encoding (issue #26). */
        q: string;
        lang?: string;
        cursor?: string | null;
        page_count?: number;
        sets?: string[];
        colors?: string[];
        color_operator?: string;
        cmc_min?: number | null;
        cmc_max?: number | null;
        types?: string[];
        rarities?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_card_by_name_cards__name__get: {
    parameters: {
      query?: {
        lang?: string;
        set?: string | null;
      };
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OracleCard"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_root_dnd_ruling__question__get: {
    parameters: {
      query?: {
        paragraph_counts?: number;
      };
      header?: never;
      path: {
        question: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_root_mtg_ruling__question__get: {
    parameters: {
      query?: {
        paragraph_counts?: number;
      };
      header?: never;
      path: {
        question: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  ocr_file_ocr__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_ocr_file_ocr__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_root_ping_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  get_sets_sets_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Sets"];
        };
      };
    };
  };
}
