// API client for MTG card search

import type { components } from "./api-types";

// Response shapes are generated from the API's own OpenAPI document
// (../openapi.json, regenerated by `just openapi-types`), not written here
// by hand. The hand-written versions had already drifted: they declared a
// set_count the API has never returned, and typed set/set_name/released_at
// on a printing as always present when the projection can omit any of them.
// normaliseCard below is what that drift cost.
export type OracleCard = components["schemas"]["OracleCard"];
export type SearchResultCard = components["schemas"]["SearchResultCard"];
export type CardPrinting = components["schemas"]["CardPrinting"];
export type SearchResponse = components["schemas"]["SearchResponse"];

// Requests are still declared by hand. The API takes its filters as a dozen
// individual query parameters rather than a body, so there is no request
// schema in the document to generate this from.
export interface CardFilter {
  sets?: string[]; // API expects "sets" not "selected_sets"
  colors?: string[];
  color_operator?: "or" | "and" | "exactly";
  cmc_min?: number;
  cmc_max?: number;
  types?: string[];
  rarities?: string[];
}

// Aggregated cards are keyed on the oracle_id. The API now exposes that as
// "id", but older builds returned MongoDB's raw "_id", and the two images
// deploy independently - so accept either and always hand back "id".
//
// Typed on SearchResultCard because it is OracleCard plus an optional score,
// so one function covers both endpoints that return an aggregated card.
type RawOracleCard = Omit<SearchResultCard, "id"> & { id?: string; _id?: string };

function normaliseCard(raw: RawOracleCard): SearchResultCard {
  const { _id, ...rest } = raw;
  const id = rest.id ?? _id ?? "";

  // Neither key means the API broke its own contract - OracleCard declares id
  // required. Issue #22 was exactly this: reversible cards have no top-level
  // oracle_id to group on, so they came back keyed null, and the "" below was
  // handed to CardTile as href="/card/". The card is still returned, because
  // dropping it would shorten the page for a reason nobody could see; but the
  // violation is logged instead of being absorbed, and CardTile no longer
  // renders an unlinkable card as a link.
  if (!id) {
    console.warn(`[api] card has no id and cannot be linked: ${rest.name ?? "<unnamed>"}`);
  }

  return { ...rest, id };
}

// Server-side only. These are called from server components, so the fetch
// runs in the Next.js process inside the Docker network and the API is never
// addressed by the browser. There is no client-callable wrapper around them:
// no route handler, no proxy rewrite, no server action.
//
// API_URL is a plain (non-NEXT_PUBLIC) variable on purpose: it is read at
// runtime on the server and never inlined into the client bundle, so the
// API hostname does not leave the network.
const API_BASE_URL = process.env.API_URL ?? "http://api:8000";

// A card, aggregated across its printings, is effectively immutable: it only
// changes when a new printing ships or oracle text is errata'd. Cache it for
// an hour so a card is fetched once and served from the cache after that.
//
// Next.js does not cache fetches by default, so this has to be asked for. The
// tag lets a single card be invalidated with revalidateTag() without waiting
// out the hour.
const CARD_REVALIDATE_SECONDS = 60 * 60;

export async function searchCards(
  text: string,
  cursor?: string | null,
  filters?: CardFilter
): Promise<SearchResponse> {
  // The search text is a query parameter, not a path segment. As a segment a
  // name containing "//" was unroutable: encodeURIComponent produced %2F, the
  // ASGI server decoded it back before routing, and FastAPI's {text} segment
  // is [^/]+ so the route stopped matching. Split and transforming cards are
  // all named that way, and this app renders those names itself (issue #26).
  const params = new URLSearchParams({
    q: text,
    lang: "en",
    page_count: "20",
  });

  if (cursor) {
    params.append("cursor", cursor);
  }

  // Add filter parameters as query params
  if (filters) {
    // Add sets (can be multiple)
    if (filters.sets && filters.sets.length > 0) {
      for (const set of filters.sets) {
        params.append("sets", set);
      }
    }

    // Add colors (can be multiple)
    if (filters.colors && filters.colors.length > 0) {
      for (const color of filters.colors) {
        params.append("colors", color);
      }
    }

    // Add color operator
    if (filters.color_operator) {
      params.append("color_operator", filters.color_operator);
    }

    // Add CMC filters
    if (filters.cmc_min !== undefined) {
      params.append("cmc_min", filters.cmc_min.toString());
    }
    if (filters.cmc_max !== undefined) {
      params.append("cmc_max", filters.cmc_max.toString());
    }

    // Add types (can be multiple)
    if (filters.types && filters.types.length > 0) {
      for (const type of filters.types) {
        params.append("types", type);
      }
    }

    // Add rarities (can be multiple)
    if (filters.rarities && filters.rarities.length > 0) {
      for (const rarity of filters.rarities) {
        params.append("rarities", rarity);
      }
    }
  }

  const response = await fetch(`${API_BASE_URL}/cards/search?${params.toString()}`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to search cards: ${response.statusText}`);
  }

  const data = await response.json();
  return { ...data, cards: (data.cards ?? []).map(normaliseCard) };
}

/** Fetch one card, aggregated across all of its printings, by Oracle ID. */
export async function getCardByOracleId(oracleId: string): Promise<OracleCard | null> {
  const response = await fetch(
    `${API_BASE_URL}/cards/oracle/${encodeURIComponent(oracleId)}/aggregated`,
    {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
      next: {
        revalidate: CARD_REVALIDATE_SECONDS,
        tags: ["card", `card:${oracleId}`],
      },
    }
  );

  if (response.status === 404) {
    return null;
  }

  if (!response.ok) {
    throw new Error(`Failed to fetch card: ${response.statusText}`);
  }

  return normaliseCard(await response.json());
}

export async function getAllSets(): Promise<string[]> {
  const response = await fetch(`${API_BASE_URL}/sets`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch sets: ${response.statusText}`);
  }

  const data = await response.json();
  return data.sets;
}
